---
- hosts: all
  become: yes
#  become_user: vagrant
  become_method: sudo
#  remote_user: ubuntu
# ---------- Start of exporter task ----------
  vars:
    node_exporter_version: 1.5.0
  tasks:
    - name: test connection
      ping:
    - name: create group
      group:
        name: prometheus
        state: present
    - name: create user
      user:
        name: prometheus
        group: prometheus
        createhome: no
        system: yes
        state: present
    - name: create opt directory for prometheus
      file:
        path: /opt/prometheus
        state: directory
    - name: download node exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
        dest: /opt/prometheus
    - name: unarchive node exporter
      unarchive:
        remote_src: yes
        src: /opt/prometheus/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
        dest: /opt/prometheus
    - name: create symlink to node exporter
      file:
        path: /usr/bin/node_exporter
        state: link
        src: /opt/prometheus/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
    - name: install unit file to systemd
      template:
        src: node_exporter.service
        dest: /etc/systemd/system/node_exporter.service
    - name: configure systemd to use service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: started
        name: node_exporter.service
# ---------- End of exporter task ----------

#    - name: create opt directory for prometheus conf
#      file: path=/opt/{{ item }} state=directory
#      with_nested:
#        - ['mon']
#        - ['mon/provision/dashboards']
#        - ['mon/provision/datasources']
#        - ['mon/provision/json']
#        - ['prom']

    - name: Copy multiple files
      file: path={{ item.path }} state={{ item.state }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
      loop:
        - { "path": "/opt/mon",  "state":  'directory', "owner":  'vagrant', "group": 'vagrant', "mode":   '0775', }
        - { "path": "/opt/mon/provision/dashboards", "state":  'directory',  "owner":  'vagrant', "group": 'vagrant', "mode":   '0775', }
        - { "path": "/opt/mon/provision/datasources", "state":  'directory', "owner":  'vagrant', "group": 'vagrant', "mode":   '0775', }
        - { "path": "/opt/mon/provision/json", "state":  'directory', "owner":  'vagrant', "group": 'vagrant', "mode":   '0775', }
        - { "path": "/opt/prom", "state":  'directory', "owner":  'vagrant', "group": 'vagrant', "mode":   '0775', }

    - name: Copy multiple files
      copy: src={{ item.src }} dest={{ item.dest }} remote_src=yes
      with_items:
        - { src: '/vagrant/prometheus-conf.yml', dest: '/opt/prom/prometheus.yml' }
        - { src: '/vagrant/docker-compose.yml', dest: '/opt/mon/docker-compose.yml' }
        - { src: '/vagrant/GF-dashboards.yml', dest: '/opt/mon/provision/dashboards/GF-dashboards.yml' }
        - { src: '/vagrant/GF-datasources-prom9090.yml', dest: '/opt/mon/provision/datasources/GF-datasources-prom9090.yml' }
        - { src: '/vagrant/GF-dashboard-1860.json', dest: '/opt/mon/provision/json/GF-dashboard-1860.json' }

    - name: Install docker-compose
      apt:
        name: docker-compose
        state: present
        update_cache: yes

    - name: Run container
      shell:
        cmd: "docker-compose up -d"
        chdir: /opt/mon/
